### ISSUE TITLE
Slashing visuals are suddenly white

### ISSUE THREAD

**Issue by 666xTaurus** [flammpfeil/SlashBlade#114]
Yesterday, I was playing with a small modpack I made centered around SlashBlade. I made a creative world (_world 1_) to test the mod, and it worked fine. Then I created a survival world (_world 2_) to actually play with the mod. Later, I crafted Ruby and it worked fine, when I right-clicked, the slashing had a red color, as it should.

Later on, I noticed that the slashing suddenly became white with no apparent reason. I went back to the creative world, but the slashing had a red color there. After that, I created a new world (_world 3_), but the slashing was white there too.

It wasn't just Ruby that had a white slashing effect, but **every** sword in the mod.

The Judgement Cut and the Mirage Edge (or mouse 3) are colored.

What I tried:
- Change video settings
- Take out every mod from the modpack, leaving only SlashBlade in it
- Relaunch the game
- Restart my computer
- Delete config files

None of the above worked.

Images (_the captions are below every image_):
https://imgur.com/a/HUd69Dn

Edit: I'm playing on the 1.20.1 version

**Comment by flammpfeil** [comment]
https://github.com/flammpfeil/SlashBlade_2/commit/8c8129af382d02e053b64211096468aa87127c80
