### ISSUE TITLE
Refining bugs [1.7.10 - r84]

### ISSUE THREAD

**Issue by KryptonCaptain** [flammpfeil/SlashBlade#13]
I was testing the fix on r84, by adding tiny soul to my sword to repair/refine it, and got this
http://i.imgur.com/3VMHcxh.png
Tried to shift-click repaired sword out from last slot, and game froze (not responding). Sword was missing when I restarted

Tested with spawned in sword to try and recreate, and found that swords can be refined without having any damage to them, if you can pay xp cost.
http://i.imgur.com/tJN4ecl.png

Did refine costs get changed at some point to be more than 1 xp level per soul used?

**Comment by flammpfeil** [comment]
Do you use the "Inventory Tweaks"?
I think it is conflict, it is please do not use "ShiftClick" because they do not know what to do.

Yes.
Always it has been the *soul to be able to use in the Anvil.
*tiny/proud/ingot/sphere/crystal
