### ISSUE TITLE
[1.9.4] Placing any blade in a crafting station from Tinkers Construct causes crash

### ISSUE THREAD

**Issue by patrickclank9** [flammpfeil/SlashBlade#14]
Crashlog upon putting in the blade: http://paste.ee/p/KFsQ2
And it keeps crashing it upon loading the world. Removal of the station with mc edit fixed it.
I also tried disabling the table rendering. Didn't work.
Other thread: https://github.com/SlimeKnights/TinkersConstruct/issues/2188

**Comment by flammpfeil** [comment]
thanks.
change commit: cf34263
fix: IbakedModel hack > use TESR
