### ISSUE TITLE
Attack animation rendering issues

### ISSUE THREAD

**Issue by schindlershadow** [flammpfeil/SlashBlade#17]
Using any version of SlashBlade from minecraft 1.8-1.10 if another player attacks with a SlashBlade sword it will messup the rendering on the screen of all players looking at that player.

ごめん、僕の日本語は下手ですけど頑張ります。SlashBladeのマインクラフトバージョン1.8から、他人はSlashBladeの剣で攻撃したらレンダリングがバラバラする。

**Comment by flammpfeil** [comment]
thanks.
