### ISSUE TITLE
[1.7.10]Client get kicked from server when middle-click sword

### ISSUE THREAD

**Issue by anqin1995** [flammpfeil/SlashBlade#18]
`[21:26:18] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NoClassDefFoundError: javax/vecmath/Matrix4d
        at mods.flammpfeil.slashblade.entity.EntitySpiralSwords.faceEntityStandby(EntitySpiralSwords.java:297) ~[EntitySpiralSwords.class:?]
...
`

Doesn't have this issue when playing locally, but get kicked on a server when player tries to middle click and hold mouse. I tried install vecmath jar in my Java installation, but does not work. My server version is 1.7.10 Thermos (also tried Cauldron, and client also gets kicked)

**Comment by flammpfeil** [comment]
You need to install the Java3D library on the server side.

**Comment by anqin1995** [comment]
Thank you for your reply! 

I have tried:

- copy the lib folder extracted to /usr/lib/jvm/java-8-oracle/jre (my Java installation destination)
- explicitly set -classpath to contain three jars and -Djava.library.path for libj3dcore-ogl.so on the command line arguments
- set environment of CLASSPATH and LD_LIBRARY_PATH as outlined in README

but none of these worked..

**Comment by flammpfeil** [comment]
Need package is "vecmath"
Not j3dcore

**Comment by anqin1995** [comment]
OK, I added it into libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar , and also libraries/javax/vecmath/1.5.2/vecmath-1.5.2.jar, and it still crashes. How should I go about installing vecmath? Thank you for taking the time replying.

**Comment by anqin1995** [comment]
OK, I resolved this by modifying Manifest.mf.
