### ISSUE TITLE
Crash after using Slash Blade (secret art)

### ISSUE THREAD

**Issue by IceLagTun** [flammpfeil/SlashBlade#22]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.40-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 7/17/16 11:39 PM
Description: Rendering entity in world

mods.flammpfeil.slashblade.client.model.obj.ModelFormatException: IO Exception reading model format
	at mods.flammpfeil.slashblade.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:58)
	at mods.flammpfeil.slashblade.client.renderer.entity.RenderSlashDimension.renderModel(RenderSlashDimension.java:75)
	at mods.flammpfeil.slashblade.client.renderer.entity.RenderSlashDimension.func_76986_a(RenderSlashDimension.java:60)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:801)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1844)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: flammpfeil.slashblade:model/util/slashdim.obj
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
	at mods.flammpfeil.slashblade.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:53)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mods.flammpfeil.slashblade.client.model.obj.WavefrontObject.<init>(WavefrontObject.java:58)
	at mods.flammpfeil.slashblade.client.renderer.entity.RenderSlashDimension.renderModel(RenderSlashDimension.java:75)
	at mods.flammpfeil.slashblade.client.renderer.entity.RenderSlashDimension.func_76986_a(RenderSlashDimension.java:60)

-- Entity being rendered --
Details:
	Entity Type: flammpfeil.slashblade.SlashDimension (mods.flammpfeil.slashblade.entity.EntitySlashDimension)
	Entity ID: 216982
	Entity Name: entity.flammpfeil.slashblade.SlashDimension.name
	Entity's Exact location: 9.97, 71.89, 61.27
	Entity's Block location: World: (9,71,61), Chunk: (at 9,4,13 in 0,3; contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: mods.flammpfeil.slashblade.client.renderer.entity.RenderSlashDimension@4fad5c3e
	Location: 4.80,0.89,-0.09 - World: (4,0,-1), Chunk: (at 4,0,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 0.0
	Delta: 0.12175584
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:801)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1844)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['l_Neko_l'/506, l='MpServer', x=5.31, y=71.00, z=61.37]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 508937 game time, 508937 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntityZombie['Zombie'/216706, l='MpServer', x=26.50, y=38.00, z=-0.50], EntityCow['Cow'/216001, l='MpServer', x=-41.20, y=69.00, z=96.52], EntityCow['Cow'/216000, l='MpServer', x=-40.51, y=67.00, z=102.20], EntitySkeleton['Skeleton'/216967, l='MpServer', x=-59.50, y=14.00, z=9.50], EntityCow['Cow'/216006, l='MpServer', x=-8.85, y=82.00, z=108.47], EntityCreeper['Creeper'/216454, l='MpServer', x=7.53, y=50.23, z=76.61], EntityBladeStand['BladeStand'/216009, l='MpServer', x=1.50, y=71.00, z=59.50], EntityCow['Cow'/216015, l='MpServer', x=54.20, y=79.00, z=17.50], EntityZombie['Zombie'/216975, l='MpServer', x=-39.50, y=71.00, z=1.50], EntityHorse['Skeleton Horse'/216012, l='MpServer', x=18.62, y=67.39, z=63.58], EntityCow['Cow'/216017, l='MpServer', x=74.05, y=66.00, z=108.37], EntityCow['Cow'/216016, l='MpServer', x=54.51, y=74.00, z=36.23], EntitySlashDimension['entity.flammpfeil.slashblade.SlashDimension.name'/216982, l='MpServer', x=9.97, y=71.89, z=61.27], EntityXPOrb['Experience Orb'/199893, l='MpServer', x=-107.89, y=70.00, z=132.93], EntityCow['Cow'/223, l='MpServer', x=32.20, y=71.00, z=124.45], EntityCow['Cow'/224, l='MpServer', x=8.52, y=72.00, z=131.82], EntityHorse['Skeleton Horse'/216160, l='MpServer', x=-10.37, y=80.00, z=-7.00], EntityBat['Bat'/216928, l='MpServer', x=31.62, y=18.25, z=41.79], EntityBat['Bat'/216875, l='MpServer', x=-17.39, y=40.04, z=66.91], EntityCow['Cow'/236, l='MpServer', x=29.53, y=71.00, z=128.20], EntityCow['Cow'/216109, l='MpServer', x=76.48, y=80.00, z=13.81], EntityXPOrb['Experience Orb'/199789, l='MpServer', x=-107.90, y=70.00, z=130.57], EntityCow['Cow'/216108, l='MpServer', x=72.80, y=80.00, z=6.59], EntityXPOrb['Experience Orb'/199788, l='MpServer', x=-106.63, y=70.00, z=131.48], EntityCow['Cow'/216178, l='MpServer', x=20.53, y=75.00, z=9.85], EntitySkeleton['Skeleton'/216951, l='MpServer', x=-0.50, y=25.00, z=85.50], EntityCow['Cow'/215995, l='MpServer', x=-72.82, y=87.00, z=34.49], EntityCow['Cow'/216186, l='MpServer', x=22.94, y=81.00, z=-14.55], EntityCow['Cow'/216185, l='MpServer', x=16.15, y=75.00, z=5.47], EntityPlayerSP['l_Neko_l'/506, l='MpServer', x=5.31, y=71.00, z=61.37], EntityCow['Cow'/215999, l='MpServer', x=-42.40, y=69.00, z=105.82], EntityCow['Cow'/215998, l='MpServer', x=-43.20, y=81.00, z=47.51], EntityCow['Cow'/216126, l='MpServer', x=60.45, y=76.00, z=9.45]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 934268920 bytes (890 MB) / 2099249152 bytes (2002 MB) up to 2099249152 bytes (2002 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.1.2011 Optifine OptiFine_1.10.2_HD_U_C2 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2011.jar) 
	UCHIJAAAA	Forge{12.18.1.2011} [Minecraft Forge] (forge-1.10.2-12.18.1.2011.jar) 
	UCHIJAAAA	bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.10.2.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10-alpha-1.0.0.jar) 
	UCHIJAAAA	JEI{3.7.6.231} [Just Enough Items] (jei_1.10.2-3.7.6.231.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-50} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-50.jar) 
	UCHIJAAAA	cyclopscore{0.7.2} [Cyclops Core] (CyclopsCore-1.9.4-0.7.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.40-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.40-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.70_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.70_beta.jar) 
	UCHIJAAAA	evilcraft{0.10.6} [EvilCraft] (EvilCraft-1.9.4-0.10.6.jar) 
	UCHIJAAAA	forestry{5.1.12.200} [Forestry] (forestry_1.10.2-5.1.12.200.jar) 
	UCHIJAAAA	gendustry{1.6.4.7} [GenDustry] (gendustry-1.6.4.7-mc1.10.2.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	Schematica{1.7.8.149} [Schematica] (Schematica-1.10.2-1.7.8.149-universal.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.9.4-r15} [SlashBlade] (SlashBlade-mc1.9.4-r15.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.40-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	List of loaded APIs: 
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.2-50.jar
		* CoFHAPI (1.8.9R1.2.0B1) from extrautils2-1.10-alpha-1.0.0.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from forestry_1.10.2-5.1.12.200.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.70_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.70_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.70_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.70_beta.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|core (5.0.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|greenhouse (5.0.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.10.2-5.1.12.200.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.1.12.200.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.7-mc1.10.2.jar
		* JustEnoughItemsAPI (4.0.0) from jei_1.10.2-3.7.6.231.jar
		* SchematicaAPI (1.1) from Schematica-1.10.2-1.7.8.149-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.10.2-1.7.8.149-universal.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Tokyo%20Fox/AppData/Roaming/.minecraft/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/TileEnergyHandler.class

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2011
	LWJGL: 2.9.4
	OpenGL: Radeon X1600/X1650 Series  GL version 2.1.8545 Release, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.10.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E6550 @ 2.33GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.8545 Release
	OpenGlRenderer: Radeon X1600/X1650 Series 
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by flammpfeil** [comment]
use 1.9.4-r15?
fix 1.9.4-r15b (missing resource file / repackaged)

**Comment by IceLagTun** [comment]
Now it works. Thank you.
