### ISSUE TITLE
1.11 - No proudsouls when katana breaks

### ISSUE THREAD

**Issue by RViper80** [flammpfeil/SlashBlade#34]
It seems with the 1.11 version of SlashBlade, Proud Souls aren't dropping when a katana breaks.  I have well over 1000 ProudSoul on both a rust edge and Sharpness-White katanas, but didn't get any from either one.

I used a name tag on a zombie, and did get the enchanted Proud Soul from that kill as normal.

**Comment by flammpfeil** [comment]
Thanks.
fix :81f7e76

**Comment by RViper80** [comment]
Thanks for the quick fix, working as it was in the older versions now :)
