### ISSUE TITLE
Config question

### ISSUE THREAD

**Issue by wilsondgonzales** [flammpfeil/SlashBlade#38]
Just wanted to ask what the values in the config for rank up range, points, and taunt represent. I can't seem to find any information on it

**Comment by flammpfeil** [comment]
RankpointRange
decrement speed factor
speed up min:50 < default:100 < max:500 slow down

RankpointUpRateTaunt
Taunt: Bonus in action to store a sword after attack with a blade.
When the enemy is around, you can rank up with high efficiency.
Rise ratio　percentage min:1% < default:150% < max:200%
% sign is not required

RankpointUpRate
Rank up point multiplier for all actions.
Rise ratio percentage min:1% < default:100% < max:200%
% sign is not required

**Comment by wilsondgonzales** [comment]
thank you for the explanation
