### ISSUE TITLE
slashblade{mc1.11-r6} crashes dedicated Forge 1.11.2 build 2226 on startup

### ISSUE THREAD

**Issue by kreezxil** [flammpfeil/SlashBlade#42]
Notes:
     lot's of classes not found, looks like you let a client side method or class slip into the server zone

crash report:
https://gist.github.com/886236b9c2fdbf74c104007d02b99a5f

fml server latest:
https://gist.github.com/75e47a2d12cb36c84d278b895f524bf8

**Comment by flammpfeil** [comment]
thanks.
fix: 22655c8
