### ISSUE TITLE
Possible kick from the server, when using a katana

### ISSUE THREAD

**Issue by Vitali8** [flammpfeil/SlashBlade#58]
When a player uses a katana, suddenly, he may be kicked from the server, it does not matter is this the first hit by katana or the fifty first hit, with such [a message to the server console](https://gist.github.com/Vitali8/64b2e418aae6fbad98733b7dfb6bc0a6).
Forge: 1.12.2-14.23.4.2705;
Server: spongeforge-1.12.2-2705-7.1.0-BETA-3221.

**Comment by flammpfeil** [comment]
fixed: 934e31b525841b0d39ad55c8d71aac8e953599e1
