### ISSUE TITLE
Crash When Starting Game

### ISSUE THREAD

**Issue by Ribbons0121R121** [flammpfeil/SlashBlade#59]
so i installed the mod and when i tried to start the game, this happens...
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-Mod-1.12.2.jar)
  SmoothWaterCore (Smooth-Water-Mod-1.12.2.jar)
  MMFMLCorePlugin (Multi-Mine-Mod-1.12.2.jar)
  NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.3.3.ALPHA.jar)
  Plugin (NotEnoughIDs-1.12.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/8/18 7:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SlashBlade (flammpfeil.slashblade)
Caused by: java.lang.NoSuchFieldError: proudSoul
	at net.langball.thaumkatana.BladeInit.init(BladeInit.java:65)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1008_BladeInit_init_InitEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at mods.flammpfeil.slashblade.SlashBlade.init(SlashBlade.java:445)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.12.6
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1516525520 bytes (1446 MB) / 3072327680 bytes (2930 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 111 mods loaded, 111 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version              | Source                                        | Signature                                |
	|:----- |:----------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft               | 1.12.2               | minecraft.jar                                 | None                                     |
	| UCHI  | mcp                     | 9.42                 | minecraft.jar                                 | None                                     |
	| UCHI  | FML                     | 8.0.99.99            | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                   | 14.23.5.2768         | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | abyssalcraft            | 1.9.4.12             | AbyssalCraft-1.12.2-1.9.4.12.jar              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHI  | additionalbanners       | 1.1.40               | Additional-Banners-Mod-1.12.2.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | orbis_api               | 1.12.2-1.1.91        | orbis_api-1.12.2-1.1.91.jar                   | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHI  | aether                  | 1.12.2-1.1.0         | aether_ii-1.12.2-1.1.0.jar                    | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHI  | aether_legacy           | 1.12.2-v3.2          | aether_legacy-1.12.2-v3.2.jar                 | None                                     |
	| UCHI  | aether_legacy_addon     | 1.12.2-v1.0          | aether_legacy_addon_1.12.2-v1.0.jar           | None                                     |
	| UCHI  | ambientsounds           | 2.0.0                | AmbientSounds v2.0.8 mc1.12.jar               | None                                     |
	| UCHI  | antiqueatlas            | 4.4.9                | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
	| UCHI  | antiqueatlasoverlay     | 1.2                  | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
	| UCHI  | examplemod              | 1.0                  | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
	| UCHI  | atlasextras             | 1.3                  | AtlasExtras-1.12.2-1.3.jar                    | None                                     |
	| UCHI  | quark                   | r1.5-130             | Quark-r1.5-130.jar                            | None                                     |
	| UCHI  | autoreglib              | 1.3-20               | AutoRegLib-1.3-20.jar                         | None                                     |
	| UCHI  | baubles                 | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHI  | chattweaks              | 5.1.8                | Better-Minecraft-Chat-Mod-1.12.2.jar          | None                                     |
	| UCHI  | boosterrockets          | 1.1.1                | BoosterRockets-1.1.1.jar                      | None                                     |
	| UCHI  | chiselsandbits          | 14.22                | Chisels-and-Bits-Mod-1.12.2.jar               | None                                     |
	| UCHI  | cvt                     | 0.1                  | chromaticvt1.2.jar                            | None                                     |
	| UCHI  | codechickenlib          | 3.2.1.351            | CodeChickenLib-1.12.2-3.2.1.351-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | coherentvillages        | 1.5.3.0              | Coherent-Villages-Mod-1.12.2.jar              | None                                     |
	| UCHI  | colytra                 | 1.1.0                | colytra-1.12.2-1.1.0.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI  | cosmeticwings           | 1.12.1-0.5.5         | Cosmetic-Wings-Mod-1.12.1.jar                 | None                                     |
	| UCHI  | cosmiclib               | 0.3.3                | CosmicLib-1.12.2-0.3.3.ALPHA.jar              | d3974446c00f9f1d275edce305771eeddf30c658 |
	| UCHI  | customnpcs              | 1.12                 | Custom-NPCs-Mod-1.12.2.jar                    | None                                     |
	| UCHI  | deathquotes             | 1.2.0                | Death-Quotes-Mod-1.12.jar                     | None                                     |
	| UCHI  | decorativefluidinjector | 1.0.1                | Decorative-Fluid-Injector-Mod-1.12.2.jar      | None                                     |
	| UCHI  | dungeontactics          | DT-0.14.9            | Dungeon-Tactics-Mod-1.12.2.jar                | None                                     |
	| UCHI  | dsurround               | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI  | presets                 | 3.4.9.16             | DynamicSurroundings-1.12.2-3.4.9.16.jar       | None                                     |
	| UCHI  | endercompass            | 1.2.6.2              | Ender-Compass-Mod-1.12.2.jar                  | None                                     |
	| UCHI  | forgemultipartcbe       | 2.4.0.55             | Forge-Multipart-1.12.2.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | microblockcbe           | 2.4.0.55             | Forge-Multipart-1.12.2.jar                    | None                                     |
	| UCHI  | minecraftmultipartcbe   | 2.4.0.55             | Forge-Multipart-1.12.2.jar                    | None                                     |
	| UCHI  | holoinventory           | 2.0.2.148            | HoloInventory-Mod-1.12.2.jar                  | None                                     |
	| UCHI  | hgp                     | Release              | Horizontal-Glass-Panes-Mod-1.12.2.jar         | None                                     |
	| UCHI  | hungeringdarkness       | 1.1.0                | Hungering+Darkness-1.12.2-1.1.0.jar           | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHI  | waila                   | 1.8.20               | Hwyla-Mod-1.12.1.jar                          | None                                     |
	| UCHI  | impart                  | 1.12.2               | Impart-Mod-1.12.2.jar                         | None                                     |
	| UCHI  | longerdays              | 1.0.4                | longerdays-1.0.4.jar                          | None                                     |
	| UCHI  | lootablebodies          | 2.4.0                | Lootable-Bodies-Mod-1.12.2.jar                | None                                     |
	| UCHI  | lycanitesmobs           | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | arcticmobs              | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | demonmobs               | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | desertmobs              | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | forestmobs              | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | freshwatermobs          | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | infernomobs             | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | junglemobs              | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | mountainmobs            | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | plainsmobs              | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | saltwatermobs           | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | shadowmobs              | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | swampmobs               | 1.17.1.4 - MC 1.12.2 | LycanitesMobsComplete 1.17.1.4 [1.12.2].jar   | None                                     |
	| UCHI  | malisiscore             | 1.12.2-6.4.0         | MalisisCore-1.12.2.jar                        | None                                     |
	| UCHI  | malisisdoors            | 1.12.2-7.3.0         | MalisisDoors-Mod-1.12.2.jar                   | None                                     |
	| UCHI  | mantle                  | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UCHI  | mapgadgets              | @VERSION@            | Mapmakers-Gadgets-Mod-1.12.2.jar              | None                                     |
	| UCHI  | joypadsplitscreenmod    | 1.12.0-0.22          | MCJoypad-Mod-1.12.2.jar                       | None                                     |
	| UCHI  | minecoprocessors        | 1.12.2-5             | Minecoprocessors-Mod-1.12.2.jar               | None                                     |
	| UCHI  | moreplayermodels        | 1.12.2               | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
	| UCHI  | multimine               | 1.5.8                | Multi-Mine-Mod-1.12.2.jar                     | None                                     |
	| UCHI  | natura                  | 1.12.2-4.3.2.62      | natura-1.12.2-4.3.2.62.jar                    | None                                     |
	| UCHI  | nex                     | 2.1.14.15            | NetherEx-Mod-1.12.2.jar                       | None                                     |
	| UCHI  | neid                    | 1.5.4.2              | NotEnoughIDs-1.12.1.jar                       | None                                     |
	| UCHI  | ordinarycoins           | 1.3.2                | Ordinary-Coins-Mod-1.12.2.jar                 | None                                     |
	| UCHI  | ore_reeds               | 1.12.2-1.0.3         | Ore-Reeds-Mod-1.12.2.jar                      | None                                     |
	| UCHI  | parry                   | 1.0                  | parry-1.0-hotfix.jar                          | None                                     |
	| UCHI  | potioncore              | 1.6_for_1.12.2       | Potion-Core-1.12.2.jar                        | None                                     |
	| UCHI  | randomtweaks            | 1.12.2-2.1.7.0       | randomtweaks-1.12.2-2.1.7.0.jar               | None                                     |
	| UCHI  | llibrary                | 1.7.15               | llibrary-1.7.15-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHI  | dragonmounts            | 1.12.2-1.4.4         | Realm-of-The-Dragons-Mod-1.12.2.jar           | None                                     |
	| UCHI  | realworld               | 1.18                 | RealWorld-Mod-1.12.2.jar                      | None                                     |
	| UCHI  | sandro                  | 1.3 BETA-2           | Redstone+++ver1.3+BETA-2.jar                  | None                                     |
	| UCHI  | redstoneplusplus        | 1.3 BETA-2           | Redstone+++ver1.3+BETA-2.jar                  | None                                     |
	| UCHI  | redstonepaste           | 1.7.5                | Redstone-Paste-Mod-1.12.1.jar                 | None                                     |
	| UCHI  | selim_enchants          | 2.1.0                | Selim's+Enchantments-1.12.2-2.1.0.jar         | None                                     |
	| UCHI  | harvest                 | 1.12-1.2.6-18        | SimpleHarvest-Mod-1.12.2.jar                  | None                                     |
	| UCHEE | flammpfeil.slashblade   | mc1.12.1-r3          | SlashBlade-Mod-1.12.1.jar                     | None                                     |
	| UCH   | tickratechanger         | 1.0.14               | TickrateChanger-1.0.14.jar                    | None                                     |
	| UCH   | sleepingoverhaul        | 0.1.2                | SleepingOverhaul-1.12.2-0.1.2.BETA.jar        | d3974446c00f9f1d275edce305771eeddf30c658 |
	| UCH   | v0idssmartbackpacks     | 1.0.3                | Smart-Backpacks-Mod-1.12.2.jar                | None                                     |
	| UCH   | smokefilter1122         | 1.1.0                | Smoke-Filter-Mod-1.12.2.jar                   | None                                     |
	| UCH   | smoothwater             | 0.1.3                | Smooth-Water-Mod-1.12.2.jar                   | None                                     |
	| UCH   | solarfurnace            | 1.0                  | SolarFurnace-Mod-1.12.2.jar                   | None                                     |
	| UCH   | soundfilters            | 0.10_for_1.12        | Sound-Filters-Mod-1.12.jar                    | None                                     |
	| UCH   | sm                      | 1.1                  | Sunglasses+and+more+1.1.jar                   | None                                     |
	| UCH   | stg                     | 1.12-1.2.1           | SwingThroughGrass-Mod-1.12.1.jar              | None                                     |
	| UCH   | tammodized              | 0.15.5               | TamModized-1.12.1-0.15.5.jar                  | None                                     |
	| UCH   | thaumcraft              | 6.1.BETA25           | Thaumcraft-1.12.2-6.1.BETA25.jar              | None                                     |
	| UCH   | thaumkatana             | 1.0.0                | Thaumickatana_V1.0.8_MC1.12.2.jar             | None                                     |
	| UCH   | tinyi                   | 1.0                  | tinyi-1.0.jar                                 | None                                     |
	| UCH   | tntplacer               | 1.0.0                | TNTPlacer.jar                                 | None                                     |
	| UCH   | toughasnails            | 3.1.0.129            | ToughAsNails-1.12.2-3.1.0.129-universal.jar   | None                                     |
	| UCH   | twilightforest          | 3.8.689              | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
	| UCH   | uncrafted               | 3.0.1                | Uncrafted-Mod-1.12.1.jar                      | None                                     |
	| UCH   | teleporter              | 1.6.3-beta4          | VanillaTeleporter-1.12-1.6.3-beta4.jar        | None                                     |
	| UCH   | imvoice                 | 0.7.0                | VoiceChat-1.12.2-0.7.0.jar                    | None                                     |
	| UCH   | voidfog                 | 1.1.3                | Void-Fog-1.1.3.jar                            | None                                     |
	| UCH   | voidcraft               | 0.26.10              | VoidCraft-1.12-0.26.10.jar                    | None                                     |
	| UCH   | wailaharvestability     | 1.1.11               | Waila-Harvestability-Mod-1.12.jar             | None                                     |
	| UCH   | wearables               | 1.1.3                | Wearables-Mod-1.12.1.jar                      | None                                     |
	| UCH   | wolfarmor               | 1.12.2-2.1.0-RELEASE | Wolf-Armor-Storage-Mod-1.12.2.jar             | None                                     |
	| UCH   | worldtooltips           | 1.2.5                | World-Tooltips-Mod-1.12.2.jar                 | None                                     |
	| UCH   | deathmaps               | 1.0.0                | deathmaps-1.12.2-1.0.0.jar                    | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCH   | ladylib                 | 2.1                  | Ladylib-2.1.jar                               | None                                     |
	| UCH   | lumen                   | 0.4.0                | lumen-Beta+0.4.1.jar                          | None                                     |
	| UCH   | pvj                     | 1.3.2                | Project-Vibrant-Journeys-Mod-1.12.2.jar       | None                                     |

	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-Mod-1.12.2.jar)
  pw.prok.realbench.asm.RBTransformer
SmoothWaterCore (Smooth-Water-Mod-1.12.2.jar)
  pl.asie.smoothwater.SmoothWaterTransformer
MMFMLCorePlugin (Multi-Mine-Mod-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  net.fybertech.nwr.NWRTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  c4.colytra.asm.ElytraTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  org.blockartistry.DynSurround.asm.Transformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.3.3.ALPHA.jar)
  
Plugin (NotEnoughIDs-1.12.1.jar)
  ru.fewizz.neid.asm.Transformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.25.19' Renderer: 'Intel(R) HD Graphics 6000'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.25.19
	OpenGlRenderer: Intel(R) HD Graphics 6000
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by flammpfeil** [comment]
The source of this bug is Thaumickatana.
It is possible that Thaumickatana's loading order is incorrect.
