### ISSUE TITLE
Compatibility with metamorph

### ISSUE THREAD

**Issue by Hahdrim** [flammpfeil/SlashBlade#60]
Hi!
To begin, thank you for this mod, it is great!
I would have a compatibility request.
When we have the mod [metamorph](https://minecraft.curseforge.com/projects/metamorph) installed, the katana do not appear on the model of the player anymore.
The mod still remains functional.
So, it would be to ask you if there was the possibility to make your mod compatible with mod metamorph! thank you!
(Sorry for my poor english, i'm french)

**Comment by flammpfeil** [comment]
commit:b53ca1c7fb67b161062e12009170a814e8777297
