### ISSUE TITLE
Issue: slashblade{mc1.9-r3} crashes dedicate forge server 1.9 build 1804 on startup

### ISSUE THREAD

**Issue by kreezxil** [flammpfeil/SlashBlade#8]
crash report:
https://gist.github.com/667b5e41be5880379c72

fml server latest:
https://gist.github.com/dc8c11a891a9f516e81c

**Comment by flammpfeil** [comment]
In this "SlashBlade" does not change the "potion item stack size".
Changing the maximum stack size of Potion are contrary to the specifications of the "Forge".
This crash is caused by other Mod.
