### ISSUE TITLE
Client crashed (using forge 12.16.0.1809 and slashblade mc1.9 r3

### ISSUE THREAD

**Issue by HENREX** [flammpfeil/SlashBlade#9]
[crash-2016-03-25_23.45.09-client.txt](https://github.com/flammpfeil/SlashBlade/files/189687/crash-2016-03-25_23.45.09-client.txt)

**Comment by flammpfeil** [comment]
fixed
d3013c6c3a38556bd46b73154e24574ad8b299c7
