### ISSUE TITLE
BladeStands not here?

### ISSUE THREAD

**Issue by PaulieMoly** [flammpfeil/SlashBlade#90]
Hey, I am playing on 1.7.10 r88 (the latest file) and I am trying to get the wither blade, but can't seem to find the blade stand, not even in creative mode, please update a new 1.7.10 mod file with the blade stand thx.

**Comment by flammpfeil** [comment]
To make a stand, right-click while placing an oak fence and sneak with a soul ingot holding it.
To remove, left click while sneak in empty slot.
