### ISSUE TITLE
Question. not an issue.

### ISSUE THREAD

**Issue by PaulieMoly** [flammpfeil/SlashBlade#91]
Hey, I tried searching for the question tab but i can't find so ill put it here, I am wondering if zombies can spawn with rust blades with spawners because i might be wasting time grinding a spawner for rust blades.

**Comment by flammpfeil** [comment]
Add rusty sword drop chance to all zombies.
flammpfeil.slashblade.cfg
rustblade{
    D:DirectDropChance=1.0
*1.0 = 100%

In 1.12.2, a zombie born from a spawner could be born with a rusty sword in his hand.
maybe

**Comment by PaulieMoly** [comment]
sorry to bother again, i am quite new here but where do i find the config i cant seem to find it in the folders, im on 1.7.10
